### ISSUE TITLE
Pasting from other applications does not work

### ISSUE THREAD

**Issue by alok** [bfredl/nvim-miniyank#3]
I copy text from another application (e.g. the URL for this page).

I have these mappings:

```
set clipboard=unnamed,unnamedplus
map p <Plug>(miniyank-startput)
```

**Comment by bfredl** [comment]
this might be issue #1, `clipboard=unnamed,unnamedplus` requires neovim master (just `cb=unnamedplus` or `cb=unnamed` should work on 0.1.4 though) until 0.1.5 is released.

**Comment by alok** [comment]
I'm using master. I have a `cron` job that autobuilds it every day.
- Alok

**Comment by bfredl** [comment]
Now see, you're using "startput". As the Readme suggests, it is better to map "autoput" to p:

```
map p <Plug>(miniyank-autoput)
```

**Comment by alok** [comment]
What's the difference between them?

**Comment by bfredl** [comment]
"startput" immediately starts putting from the internal yank history. "autoput" will make sure to first put the text what nonremapped "p" would have putted otherwise, including support for explicit (`"ap`) and implicit (`cb=unnamed[plus]`) register names (though the latter should be stated more clearly in the README) and therefore is best to use when remapping `p`.

**Comment by alok** [comment]
`autoput` works, thanks.
